# Generated by Django 4.2.17 on 2025-01-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_landlord_email_alter_landlord_mailing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='busines_name',
            new_name='business_name',
        ),
    ]
