# Generated by Django 4.2.17 on 2025-01-22 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_busines_name_landlord_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('monthly_rent', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('current_address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in this format: '+[Country Code][Number]'. Up to 15 digits allowed.")])),
                ('email', models.CharField(max_length=200)),
                ('monthly_rent', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='landlord',
            name='password',
            field=models.CharField(default='Please enter your password.', max_length=50),
        ),
        migrations.AddField(
            model_name='landlord',
            name='username',
            field=models.CharField(default='MDLANDLORD', max_length=500),
        ),
        migrations.CreateModel(
            name='TenantProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.tenant')),
            ],
        ),
    ]
