# Generated by Django 4.2.17 on 2025-01-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_property_tenant_alter_landlord_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.RemoveField(
            model_name='tenantproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenantproperty',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantProperty',
        ),
    ]
