# Generated by Django 4.2.17 on 2025-01-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_landlord_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenantproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenantproperty',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantProperty',
        ),
    ]
