# Generated by Django 4.2.17 on 2025-01-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_properties',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
