# Generated by Django 4.2.17 on 2025-01-27 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0010_remove_property_landlord_remove_tenant_landlord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in this format: '+[Country Code(International)][Number]'. Up to 15 digits allowed.")])),
                ('email', models.CharField(max_length=200)),
                ('mailing_address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('unit_quantity', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=200)),
                ('monthly_rent', models.PositiveBigIntegerField()),
                ('last_increase_date', models.DateField(blank=True, default=None, null=True)),
                ('rent_increase_percentage', models.IntegerField(blank=True, default=None, null=True)),
                ('ocupancy_start_date', models.DateField(blank=True, default=None, null=True)),
                ('ocupancy_status', models.CharField(max_length=25)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='files.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('current_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in this format: '+[Country Code][Number]'. Up to 15 digits allowed.")])),
                ('email', models.CharField(max_length=200)),
                ('monthly_rent', models.PositiveBigIntegerField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='files.landlord')),
                ('tenant_properties', models.ManyToManyField(related_name='properties', to='files.property')),
            ],
        ),
    ]
